"use client";
import { Button } from "@/components/ui/button";

export default function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
 // Function that handles downloading the summary as a text file
const handleDownload = () => {

  // Create the full content of the summary file using a template literal
  const summaryContent = `${title}

Generated Summary

Generated on: ${new Date(createdAt).toLocaleString("en-IN", {
  dateStyle: "medium",
  timeStyle: "short",
})}

${summaryText}

Original File: ${fileName}
Generated By Sommaire`;

  // Create a Blob object from the summary content
  // "text/plain" indicates a plain text (.txt) file
  const blob = new Blob([summaryContent], { type: "text/plain" });

  // Create a temporary URL for the Blob in browser memory
  const url = URL.createObjectURL(blob);

  // Dynamically create an anchor (<a>) element
  const link = document.createElement("a");

  // Set the download URL to the Blob URL
  link.href = url;

  // Set a safe file name by replacing special characters in the title
  link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;

  // Append the anchor to the document body (required for Firefox)
  document.body.appendChild(link);

  // Programmatically trigger a click to start the download
  link.click();

  // Remove the anchor element after triggering the download
  document.body.removeChild(link);

  // Revoke the temporary Blob URL to free browser memory
  URL.revokeObjectURL(url);
};


  return (
    <Button
      size={"sm"}
      variant={"destructive"}
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-100"
      onClick={handleDownload}
    >
      Download Summary
    </Button>
  );
}
